# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ijtfwtuAtmu837LzELOCkDjdqzL3Iq-8
"""

import re

def extract_emails_interactively():
    print("--- AUTOMATED EMAIL EXTRACTOR  ---")
    print("Paste your raw text or emails below.")
    print("When you are done pasting, type 'DONE' on a new line and press Enter to scan:")
    print("-" * 60)

    # 1. Capture multi-line pasted text dynamically from the user
    lines = []
    while True:
        line = input()
        if line.strip().upper() == "DONE":
            break
        lines.append(line)

    user_text = "\n".join(lines)

    # 2. Regular Expression (regex) pattern to match valid email structures
    email_pattern = r'[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}'

    # 3. Use 're.findall' to scan the pasted text
    found_emails = re.findall(email_pattern, user_text)

    # 4. Remove any duplicate emails using a set
    unique_emails = list(set(found_emails))

    # Display the results
    print("-" * 60)
    if unique_emails:
        print(f"🎉 Automation Complete! Found {len(unique_emails)} unique email addresses:")
        for index, email in enumerate(unique_emails, start=1):
            print(f"{index}. {email}")
    else:
        print("Bot: No valid email addresses found in your pasted text.")
    print("-" * 60)

# Run the interactive automation tool
extract_emails_interactively()